#cloud-config
fs_setup:
  - label: 'src'
    filesystem: 'xfs'
    device: '/dev/sdb'
    partition: 'auto'

mounts:
  - [sdb, /home/vscode/src]
mount_default_fields: [None, None, "xfs", "defaults", "0", "2"]
