---
- name: Install AWSCLI Prereqs
  package:
    name:
      - unzip
    state: latest
  become: true
  tags:
    - awscli

- name: Download AWSCLI Installer
  unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp
    remote_src: true
  tags:
    - awscli

- name: Install AWSCLI
  command: /tmp/aws/install
  args:
    creates: /usr/local/aws-cli
  become: true
  tags:
    - awscli
